# AutoSettings For CraftRise
# CraftRise İçin Yapılan Otomatik Ayarlardır

# Settings
# Ayarlar

AbortBreaking toggle false
AbortBreaking bind NONE
Aimbot Range 4.4
Aimbot TurnSpeed 2.0
Aimbot FOV 180.0
Aimbot Center false
Aimbot Lock true
Aimbot OnClick false
Aimbot Jitter false
Aimbot toggle false
Aimbot bind NONE
AirJump toggle false
AirJump bind NONE
AirLadder toggle false
AirLadder bind NONE
AntiAFK toggle false
AntiAFK bind NONE
AntiBot Tab true
AntiBot TabMode Contains
AntiBot EntityID true
AntiBot Color true
AntiBot LivingTime false
AntiBot Ground false
AntiBot Air false
AntiBot InvaildGround false
AntiBot Swing false
AntiBot Health true
AntiBot Derp true
AntiBot WasInvisible true
AntiBot Armor false
AntiBot Ping true
AntiBot NeedHit false
AntiBot toggle true
AntiBot bind NONE
AntiCactus toggle true
AntiCactus bind NONE
AntiHunger toggle false
AntiHunger bind NONE
AtAllProvider MaxDelay 1000
AtAllProvider MinDelay 500
AtAllProvider Retry false
AtAllProvider toggle false
AtAllProvider bind NONE
AutoArmor MaxDelay 125
AutoArmor MinDelay 75
AutoArmor InvOpen true
AutoArmor SimulateInventory true
AutoArmor NoMove true
AutoArmor ItemDelay 150
AutoArmor Hotbar true
AutoArmor toggle true
AutoArmor bind NONE
AutoBow toggle true
AutoBow bind NONE
AutoBreak toggle false
AutoBreak bind NONE
AutoClicker MaxCPS 8
AutoClicker MinCPS 5
AutoClicker Right true
AutoClicker Left true
AutoClicker Jitter false
AutoClicker toggle false
AutoClicker bind NONE
AutoFish toggle false
AutoFish bind NONE
AutoLeave Health 8.0
AutoLeave Mode Quit
AutoLeave toggle false
AutoLeave bind NONE
AutoPot Health 10.0
AutoPot Delay 150
AutoPot OpenInv true
AutoPot NoAir false
AutoPot Mode Normal
AutoPot toggle true
AutoPot bind NONE
AutoRespawn Instant true
AutoRespawn toggle true
AutoRespawn bind NONE
AutoSoup Health 15.0
AutoSoup Delay 150
AutoSoup OpenInv false
AutoSoup toggle false
AutoSoup bind NONE
AutoTool toggle true
AutoTool bind NONE
AutoWalk toggle false
AutoWalk bind NONE
AutoWeapon SpoofItem false
AutoWeapon toggle true
AutoWeapon bind NONE
BedGodMode toggle false
BedGodMode bind NONE
Blink Pulse false
Blink PulseDelay 1000
Blink toggle false
Blink bind NONE
BlockWalk Cobweb true
BlockWalk Snow true
BlockWalk toggle false
BlockWalk bind NONE
BowAimbot Silent true
BowAimbot Predict true
BowAimbot ThroughWalls false
BowAimbot PredictSize 2.0
BowAimbot Priority Direction
BowAimbot Mark true
BowAimbot toggle true
BowAimbot bind NONE
BufferSpeed SpeedLimit true
BufferSpeed MaxSpeed 2.0
BufferSpeed Buffer true
BufferSpeed Stairs true
BufferSpeed StairsBoost 1.87
BufferSpeed StairsMode New
BufferSpeed Slabs true
BufferSpeed SlabsBoost 1.87
BufferSpeed SlabsMode New
BufferSpeed Ice false
BufferSpeed IceBoost 1.342
BufferSpeed Snow true
BufferSpeed SnowBoost 1.87
BufferSpeed SnowPort true
BufferSpeed Wall true
BufferSpeed WallBoost 1.87
BufferSpeed WallMode New
BufferSpeed HeadBlock true
BufferSpeed HeadBlockBoost 1.87
BufferSpeed Slime true
BufferSpeed AirStrafe false
BufferSpeed NoHurt true
BufferSpeed toggle false
BufferSpeed bind NONE
BugUp Mode FlyFlag
BugUp MaxFallDistance 10
BugUp MaxDistanceToSetback 2.5
BugUp Indicator true
BugUp toggle false
BugUp bind NONE
ChestAura Range 5.0
ChestAura Delay 100
ChestAura ThroughWalls false
ChestAura VisualSwing true
ChestAura Chest 54
ChestAura toggle false
ChestAura bind L
ChestStealer MaxDelay 125
ChestStealer MinDelay 75
ChestStealer TakeRandomized true
ChestStealer OnlyItems false
ChestStealer NoCompass false
ChestStealer AutoClose true
ChestStealer AutoCloseMaxDelay 0
ChestStealer AutoCloseMinDelay 0
ChestStealer CloseOnFull true
ChestStealer ChestTitle false
ChestStealer toggle false
ChestStealer bind K
CivBreak Range 5.0
CivBreak Rotations true
CivBreak VisualSwing true
CivBreak Air-Reset true
CivBreak Range-Reset true
CivBreak toggle false
CivBreak bind NONE
Clip Mode Flag
Clip Horizontal 0.0
Clip Vertical 5.0
Clip toggle false
Clip bind T
ComponentOnHover toggle false
ComponentOnHover bind NONE
ConsoleSpammer Mode Payload
ConsoleSpammer Delay 0
ConsoleSpammer toggle false
ConsoleSpammer bind NONE
Criticals Mode Jump
Criticals Delay 0
Criticals HurtTime 10
Criticals toggle true
Criticals bind NONE
Damage Mode NCP
Damage Damage 1
Damage toggle false
Damage bind NONE
Derp Headless false
Derp Spinny false
Derp Increment 1.0
Derp toggle false
Derp bind NONE
Eagle toggle false
Eagle bind NONE
FastBow Packets 20
FastBow toggle false
FastBow bind NONE
FastBreak BreakDamage 0.8
FastBreak toggle false
FastBreak bind NONE
FastClimb Mode Normal
FastClimb NormalSpeed 0.2872
FastClimb toggle false
FastClimb bind NONE
FastPlace Speed 0
FastPlace toggle false
FastPlace bind NONE
FastStairs Mode NCP
FastStairs LongJump false
FastStairs toggle false
FastStairs bind NONE
FastUse Mode NCP
FastUse Delay 0
FastUse toggle false
FastUse bind NONE
Fly Mode NeruxVace
Fly VanillaSpeed 2.0
Fly VanillaKickBypass false
Fly MineplexSpeed 1.0
Fly NCPMotion 0.0
Fly AACSpeed 0.3
Fly AAC3.3.12-Motion 10.0
Fly AAC3.3.13-Motion 10.0
Fly NeruxVace-Ticks 3
Fly HypixelLatest-Boost true
Fly HypixelLatest-BoostDelay 1200
Fly HypixelLatest-BoostTimer 1.0
Fly Mark true
Fly toggle false
Fly bind F
ForceUnicodeChat toggle false
ForceUnicodeChat bind NONE
Freeze toggle false
Freeze bind NONE
Fucker ID 26
Fucker Instant false
Fucker ThroughWalls None
Fucker Swing true
Fucker Rotations true
Fucker Surroundings true
Fucker Action Destroy
Fucker NoHit false
Fucker toggle false
Fucker bind NONE
Ghost toggle false
Ghost bind NONE
GhostHand ID 54
GhostHand toggle false
GhostHand bind G
GodMode toggle false
GodMode bind NONE
HighJump Height 2.0
HighJump Mode Vanilla
HighJump OnlyGlassPane false
HighJump toggle false
HighJump bind NONE
HitBox Size 0.4
HitBox toggle false
HitBox bind NONE
IceSpeed Mode NCP
IceSpeed toggle false
IceSpeed bind NONE
Ignite Lighter true
Ignite Lava true
Ignite toggle false
Ignite bind NONE
InventoryCleaner MaxDelay 125
InventoryCleaner MinDelay 75
InventoryCleaner InvOpen true
InventoryCleaner SimulateInventory true
InventoryCleaner NoMove true
InventoryCleaner Hotbar true
InventoryCleaner RandomSlot true
InventoryCleaner Sort true
InventoryCleaner ItemDelay 150
InventoryCleaner SortSlot-1 Sword
InventoryCleaner SortSlot-2 Bow
InventoryCleaner SortSlot-3 Pickaxe
InventoryCleaner SortSlot-4 None
InventoryCleaner SortSlot-5 None
InventoryCleaner SortSlot-6 Food
InventoryCleaner SortSlot-7 Food
InventoryCleaner SortSlot-8 Block
InventoryCleaner SortSlot-9 Block
InventoryCleaner toggle false
InventoryCleaner bind I
InventoryMove NoDetectable false
InventoryMove AACAdditionPro true
InventoryMove NoMoveClicks false
InventoryMove toggle true
InventoryMove bind NONE
ItemTeleport Mode New
ItemTeleport ResetAfterTP true
ItemTeleport Button Middle
ItemTeleport toggle false
ItemTeleport bind NONE
KeepAlive Mode /heal
KeepAlive toggle false
KeepAlive bind NONE
KeepContainer toggle false
KeepContainer bind NONE
Kick Mode Quit
Kick toggle false
Kick bind NONE
KillAura MaxCPS 15
KillAura MinCPS 10
KillAura HurtTime 7
KillAura Range 3.7
KillAura ThroughWallsRange 1.5
KillAura RangeSprintReducement 0.2
KillAura Priority Distance
KillAura TargetMode Single
KillAura Swing true
KillAura KeepSprint false
KillAura AutoBlock true
KillAura InteractAutoBlock false
KillAura DelayedBlock true
KillAura BlockRate 100
KillAura RayCast true
KillAura RayCastIgnored false
KillAura LivingRayCast true
KillAura AAC true
KillAura MaxTurnSpeed 125.0
KillAura MinTurnSpeed 75.0
KillAura SilentRotation true
KillAura RotationStrafe false
KillAura RandomCenter true
KillAura Outborder true
KillAura FOV 180.0
KillAura Predict true
KillAura MaxPredictSize 1.0
KillAura MinPredictSize 1.0
KillAura FailRate 1.5
KillAura FakeSwing true
KillAura NoInvAttack true
KillAura NoInvDelay 200
KillAura LimitedMultiTargets 0
KillAura Mark true
KillAura FakeSharp true
KillAura toggle false
KillAura bind R
LadderJump toggle false
LadderJump bind NONE
LiquidChat JWT false
LiquidChat toggle false
LiquidChat bind NONE
LiquidWalk Mode AAC3.3.11
LiquidWalk NoJump false
LiquidWalk AACFlyMotion 0.5
LiquidWalk toggle true
LiquidWalk bind J
Liquids toggle false
Liquids bind NONE
LongJump Mode NCP
LongJump NCPBoost 4.25
LongJump AutoJump false
LongJump toggle false
LongJump bind NONE
MidClick toggle true
MidClick bind NONE
MoreCarry toggle false
MoreCarry bind NONE
MultiActions toggle false
MultiActions bind NONE
NoClip toggle false
NoClip bind NONE
NoFall Mode SpoofGround
NoFall toggle false
NoFall bind NONE
NoFriends toggle false
NoFriends bind N
NoJumpDelay toggle true
NoJumpDelay bind NONE
NoPitchLimit ServerSide true
NoPitchLimit toggle false
NoPitchLimit bind NONE
NoRotateSet Confirm true
NoRotateSet ConfirmIllegalRotation false
NoRotateSet NoZero false
NoRotateSet toggle false
NoRotateSet bind NONE
NoSlow BlockForwardMultiplier 1.0
NoSlow BlockStrafeMultiplier 1.0
NoSlow ConsumeForwardMultiplier 1.0
NoSlow ConsumeStrafeMultiplier 1.0
NoSlow BowForwardMultiplier 1.0
NoSlow BowStrafeMultiplier 1.0
NoSlow Packet true
NoSlow Soulsand true
NoSlow toggle false
NoSlow bind NONE
NoSlowBreak Air true
NoSlowBreak Water false
NoSlowBreak toggle false
NoSlowBreak bind NONE
NoWeb Mode AAC
NoWeb toggle true
NoWeb bind NONE
Nuker Radius 5.2
Nuker ThroughWalls false
Nuker toggle false
Nuker bind NONE
Paralyze toggle false
Paralyze bind NONE
Parkour toggle false
Parkour bind NONE
PerfectHorseJump toggle false
PerfectHorseJump bind NONE
Phase Mode Skip
Phase toggle false
Phase bind P
PingSpoof MaxDelay 1000
PingSpoof MinDelay 500
PingSpoof toggle false
PingSpoof bind NONE
Plugins toggle false
Plugins bind NONE
PotionSaver toggle false
PotionSaver bind NONE
Reach CombatReach 3.5
Reach BuildReach 5.0
Reach toggle false
Reach bind NONE
Regen Mode Vanilla
Regen Health 18
Regen Food 18
Regen Speed 100
Regen NoAir false
Regen toggle false
Regen bind NONE
ResourcePackSpoof toggle false
ResourcePackSpoof bind NONE
ReverseStep Motion 1.0
ReverseStep toggle false
ReverseStep bind NONE
SafeWalk AirSafe false
SafeWalk toggle false
SafeWalk bind NONE
Scaffold Mode Normal
Scaffold MaxDelay 125
Scaffold MinDelay 75
Scaffold PlaceableDelay true
Scaffold AutoBlock false
Scaffold StayAutoBlock true
Scaffold Sprint false
Scaffold Swing true
Scaffold Search false
Scaffold PlaceTiming Post
Scaffold Eagle true
Scaffold EagleSilent false
Scaffold BlocksToEagle 1
Scaffold ExpandLength 5
Scaffold Rotations true
Scaffold KeepRotation true
Scaffold Zitter false
Scaffold ZitterMode Teleport
Scaffold ZitterSpeed 0.13
Scaffold ZitterStrength 0.072
Scaffold Timer 1.0
Scaffold SpeedModifier 0.0
Scaffold SameY false
Scaffold SafeWalk true
Scaffold AirSafe false
Scaffold Counter true
Scaffold Mark false
Scaffold toggle false
Scaffold bind H
ServerCrasher Mode AACNew
ServerCrasher toggle false
ServerCrasher bind NONE
SkinDerp Delay 0
SkinDerp Hat true
SkinDerp Jacket true
SkinDerp LeftPants true
SkinDerp RightPants true
SkinDerp LeftSleeve true
SkinDerp RightSleeve true
SkinDerp toggle false
SkinDerp bind NONE
SlimeJump Motion 0.42
SlimeJump Mode Add
SlimeJump toggle false
SlimeJump bind NONE
Sneak Mode Legit
Sneak StopMove false
Sneak toggle false
Sneak bind Z
Speed Mode Custom
Speed CustomSpeed 1.9
Speed CustomY 0.0
Speed CustomTimer 0.3
Speed CustomStrafe true
Speed CustomResetXZ false
Speed CustomResetY false
Speed AAC-PortLength 1.0
Speed AACGround-Timer 3.0
Speed CubeCraft-PortLength 1.0
Speed MineplexGround-Speed 0.5
Speed toggle false
Speed bind F
Sprint AllDirections false
Sprint Blindness true
Sprint Food true
Sprint CheckServerSide false
Sprint CheckServerSideOnlyGround false
Sprint toggle true
Sprint bind NONE
Step Mode NCP
Step Height 1.0
Step Delay 0
Step toggle true
Step bind V
Strafe toggle true
Strafe bind NONE
SuperKnockback HurtTime 10
SuperKnockback toggle false
SuperKnockback bind NONE
targetPlayer true
targetMobs false
targetAnimals false
targetInvisible false
targetDead true
TNTBlock Fuse 50
TNTBlock Range 9.0
TNTBlock AutoSword true
TNTBlock toggle true
TNTBlock bind NONE
Teams ScoreboardTeam true
Teams Color false
Teams toggle false
Teams bind NONE
Teleport Mode Blink
Teleport Button Middle
Teleport toggle false
Teleport bind NONE
TeleportHit toggle false
TeleportHit bind NONE
Timer Speed 2.0
Timer toggle false
Timer bind NONE
Tower Mode Jump
Tower AutoBlock false
Tower StayAutoBlock true
Tower Swing true
Tower StopWhenBlockAbove true
Tower Rotations true
Tower KeepRotation true
Tower OnJump false
Tower PlaceTiming Post
Tower Timer 1.0
Tower JumpMotion 0.42
Tower JumpDelay 0
Tower ConstantMotion 0.42
Tower ConstantMotionJumpGround 0.79
Tower TeleportHeight 1.15
Tower TeleportDelay 0
Tower TeleportGround true
Tower TeleportNoMotion false
Tower Counter true
Tower toggle false
Tower bind Y
Trigger MaxCPS 8
Trigger MinCPS 5
Trigger toggle false
Trigger bind NONE
VehicleOneHit toggle false
VehicleOneHit bind NONE
Velocity Horizontal 0.0
Velocity Vertical 0.0
Velocity Mode Simple
Velocity ReverseStrength 1.0
Velocity Reverse2Strength 0.05
Velocity AACPushXZReducer 2.0
Velocity AACPushYReducer true
Velocity toggle false
Velocity bind NONE
WallClimb Mode AAC3.3.12
WallClimb ClipMode Fast
WallClimb CheckerClimbMotion 0.0
WallClimb toggle false
WallClimb bind M
WaterSpeed Speed 1.2
WaterSpeed toggle false
WaterSpeed bind NONE
Zoot BadEffects true
Zoot Fire true
Zoot NoAir false
Zoot toggle false
Zoot bind NONE

chat &c&lTURN ON ANTIFORGE, OTHERWISE YOU CANT JOIN SERVER!
chat &c&lDONT USE FLY MORE THAN FEW SECONDS AND DONT SPAM THAT
chat &c%lSET FLY AND SPEED IN THE SAME BIND THEY ARE COMBINIZED FOR BYPASS
chat &c&lYou can use WallClimb for escape traps
chat &c&lDont play with high ping its bannable
chat &c&lToggles, not mean "You cant use this module" you can use other modules except bannable ones, it is just for make settings default
chat &6&lSettings made by Teals53 & xHackerBey | 03.01.2020
chat &9&lIf you have any suggestion or question you can contact us from our Discords &3&lTeals53#1508 &2&l& &3&lEgemeN#7050
chat ------------------------------------------
chat &c&lANTIFORGEYI ACMASSANIZ SUNUCUYA GIREMEZSINIZ!
chat &c&lFLYI BİRKAÇ SANİYEDEN FAZLA VE ÇOK SIK KULLANMAYIN
chat &c&lFLY VE SPEEDI AYNI TUSA ADAYIN UCMAK ICIN BIRLIKDE KOMBIN OLMUS DURUMDADIRLAR
chat &c&lTuzaklardan çıkmak için WallCLimb kullanabilirsiniz
chat &c&lYüksek ping ile oynamaktan kaçının ban yedirtebilir
chat &c&lKapali moduller "Bu modulu kullanamazsiniz" anlamina gelmez, bu sadece ayarlari normale cevirmek icindir, banlatmayan diger modulleri kullanabilirsiniz
chat &6&lBu ayarlar Teals53 ve xHackerBey tarafindan yapilmistir | 03.01.2020
chat &2&lHerhangi bir sorunuz yada oneriniz varsa bize Discorddan ulasabilirsiniz &3&lTeals53#1508 &2&l& &3&lEgemeN#7050